### PR TITLE
Move to the footer

### LINKED ISSUE #132: Move status-bar into the bottom bar
This will let `status-bar` span the full width of the window, instead of just the width of the text editor.

See https://github.com/atom/atom/pull/9274.

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #132 

untitled

### CODE REVIEW

**Comment by joshaber** [comment]
...Travis is taking a nap, I guess.

**Comment by thedaniel** [comment]
https://travis-ci.org/atom/status-bar/requests "branch not included or excluded" wat

**Comment by thedaniel** [comment]
There's a travis API endpoint for this, but close and reopen usually works - it's the "turn it on and off again" of Travis CI.

**Comment by joshaber** [comment]
Let's do this :-1:

**Comment by gluons** [comment]
I prefer old statud bar position. Did you have any setting to get it back?

**Pull request merged**
