### PR TITLE
Add package setting to toggle full-width status-bar

### PR DESCRIPTION
**Pull request by Alhadis**
I have writer's block, so I'll just echo @simurai's words, [because he put it best](https://github.com/atom/status-bar/issues/91#issuecomment-145193638):

> But somehow it feels wrong. I think the reason is because the status-bar changes based on the active editor and should somewhat stay connected to it. Full-width at the bottom it feels like it's something more global and less related to the active editor.

I agree wholeheartedly, and some other users might too. Artistic rationale aside, stubborn and change-resilient users like me would appreciate having a setting to restore the status-bar's old appearance:

Figure 1

If it needs to be said, the setting's default value is to use the full-width status bar:

Figure 2

This is how the option appears in the package's settings:

Figure 3

### CODE REVIEW

**Comment by simurai** [comment]
Here another thought: Separate the status-bar items based on if something is permanent (global) or just temporary (per file):

screen shot 2016-06-07 at 4 42 17 pm

Then the permanent items, like updates etc. could be on the left and under the "global" tree-view. On the right are all the items that change "per file". So the file name would be under the editor and look less disconnected..

..of course this falls flat for people that moved the tree-view to the right. And it might also be something that not all people like and demand the old the position back. 💭

**Comment by Alhadis** [comment]
... what we have now works perfectly fine. There's no point changing what we're already used to.

I believe many users made that point abundantly clear when v1.7.0 was released.

**Comment by pradyunsg** [comment]
I do think what has been proposed in this PR is the best compromise in the short-term.

@simurai has a nice idea. It might be a little too late to change the entire arrangement of the status-bar though.

But if someone comes up with a clean proposal for how this comes together (including not breaking the existing status-bar API), I'm all for it. It would be nice to have some organization in the status bar.

> of course this falls flat for people that moved the tree-view to the right.

No it doesn't. Just determine which side the tree-view is on (I'm assuming it's not too hard, from what I know of Atom's API).

**Comment by Alhadis** [comment]
Drag-and-drop might be nice.

**Comment by pradyunsg** [comment]
I think this idea might be worth exploring but is still fairly disconnected to what is there in this PR. 

Maybe open a new issue for discussing the separation of permanent and temporary status-bar items?

**Comment by Alhadis** [comment]
On it.

**Comment by gluons** [comment]
Wow! I really need this setting. Good news. 😄

**Comment by gh0stonio** [comment]
👍

**Comment by pierreneter** [comment]
i cant see that option in my status-bar setting @.@

**Comment by Alhadis** [comment]
> i cant see that option in my status-bar setting @.@

That's because this pull-request hasn't been merged yet...

**Comment by simurai** [comment]
I'm not so sure. It's nice to have the option, but it also adds extra complexity.

For example the One theme has a bottom border for the tree-view that should be removed if the status-bar isn't full-width. Maybe an extra class `has-full-width-status-bar` on the `body` could help, but it's another case that needs to be tested when making changes.

Is this a good candidate for the `init.coffee`?

```coffee
@statusBar = document.querySelector('.status-bar')
atom.workspace.addBottomPanel(item: @statusBar, priority: 0)
```

And depending on the theme, might need a `styles.less` tweak.

**Comment by Alhadis** [comment]
> For example the One theme has a bottom border for the tree-view that should be removed if the status-bar isn't full-width

What's wrong with moving the border to the status bar?

**Comment by Alhadis** [comment]
BTW, the `tree-view` has a package setting to control its position in the workspace as well:

Figure 1

Since it's (physically) connected to the status bar, it feels logical that the status bar would have a similar layout-influencing setting as well. I also think `init.coffee` shouldn't be a dumping ground for any settings many users aren't expected to use.

**Comment by ajmichaels** [comment]
👍 As someone who toggles the atom-linter notifications quite often, the new position is fairly annoying.

**Comment by lorenzos** [comment]
:+1:

**Comment by simurai** [comment]
I'm not entirely against this option, because options are nice to have. Just that in general, adding config options can increase complexity because you have to account for different situations and can't assume certain things anymore. And it might add an extra burden to package/theme authors to test against all the different options.

For example it's nice that the tree-view can be moved to the right, but then the notifications cover the tree-view https://github.com/atom/notifications/issues/93 which isn't ideal for some.

> I really think `init.coffee` shouldn't be a dumping ground for every setting not expected to see common use.

Yeah, it's hard to guess what is considered "common use". So I wanted to make sure that:

1. There aren't any side effects that we haven't thought about.
2. This option would have enough user adoption to warrant the cost of maintaining an extra setting.

**Comment by Alhadis** [comment]
> There aren't any side effects that we haven't thought about.

Honestly, I can't see this introducing any issues. Even in uncommon scenarios:

1. **A package author needs to apply specific styling to the status bar when contained in a certain pane:**  
[Simple CSS fix](https://github.com/atom/atom-light-ui/pull/30/files): `.panel-bottom status-bar`, `.panel-footer status-bar`.

2. **Package authors need to query or detect changes to status bar position**  
Atom's config API already covers that:
```js
atom.config.get("status-bar.fullWidth");
atom.config.observe("status-bar.fullWidth");
```

I've also added specs to guard against regressions, just in case.

> This option would have enough user adoption to warrant the cost of maintaining an extra setting.

At least seven other users who've seen this pull request have given a 👍, and a few others have even voiced their approval.

**Comment by Alhadis** [comment]
So... what's happening with this...?

**Comment by blcarson** [comment]
FWIW this change is driving me seriously batty. Is there an easy way I can get these changes in now?

**Comment by Alhadis** [comment]
Yep! `cd` to wherever you'd like to keep a forked project, and run this:

```shell
git clone https://github.com/Alhadis/status-bar.git
cd status-bar && git checkout width-setting
apm install && apm link -d .
```

**CAVAET:** This requires a project to be opened in *development mode* in order to take effect.

Which is what I've been doing every day for over two months now, and I'm getting kinda sick of it.

**Comment by blcarson** [comment]
Ahh - you're a saint!

I installed it in my ~/.atom/packages folder and it seems to work without developer mode. Any reason why you have to run through that process daily?

**Comment by Alhadis** [comment]
Erh, really? I wasn't aware Atom enabled you to "override" packages that way... to date, I've simply been repeating the steps [described here](https://github.com/atom/atom/blob/master/docs/contributing-to-packages.md#hacking-on-packages). I'm not sure this is expected behaviour.

@simurai, any idea if this is a bug?

**Comment by blcarson** [comment]
Steps I took, in case it's helpful:

- Cloned the repo to my ~/.atom/packages folder
- Ran the commands you suggested
- Opened atom in dev mode
- Enabled your package (which seemed to turn on the default one as well)
- Toggled the width option setting to off
- Started atom in normal mode and settings persisted

I'm on Mac 10.12 if it makes any difference.

screenshot

**Comment by simurai** [comment]
@Alhadis If you use `apm link` instead of `apm link -d`, then the package is available also in normal mode. The reason to use `apm link -d` while you work on a package is so that you can run both versions at the same time. A normal mode window with the published package and a dev mode window with your local package. Maybe not needed for all package, but if you mess something up locally, your normal mode window will still work as usual.

btw. the One themes got changed so that the borders wouldn't be an issue anymore.

**Comment by Alhadis** [comment]
Well, I know that... but seeing a core package listed as both a "Community Package" and a "Core "Package" looked pretty erroneous to me. But I digress.

My main question is: what's this bar's status?

**Comment by simurai** [comment]
> My main question is: what's this bar's status?

Ya, it's a bit weird that it shows the atom avatar and the download counts for your linked package that isn't really published.

**Comment by Alhadis** [comment]
Eyyyyupp, that'll teach me for trying to be punny with a vague wisecrack (`status-bar` = "bar's status"). It sounded funnier in my head, honest.

It was a fatigue-encrypted way of asking if this PR is close to being merged yet...

**Comment by simurai** [comment]
Ahh.. hehe.. :joy:

Well, I'm fine with either. But we need at least somebody else to review the code.

**Comment by Alhadis** [comment]
I'll send a Mars Bar to any Atom member who gets this and another [light-and-easy](https://github.com/atom/find-and-replace/pull/726) PR reviewed this week. For real.

I say that on the grounds nobody is insane enough to send their address so a sleep-deprived Australian can order them a chocolate bar.

**Comment by blcarson** [comment]
I'll up the ante and will donate a case of your favorite candy bar (assuming its available on Amazon Prime) to the cause 🍫

**Comment by Alhadis** [comment]
⬆️  This guy. Right across it. 👍 👌

**Comment by blcarson** [comment]
New version of status bar breaks the width setting.

**Comment by Alhadis** [comment]
Not anymore.

**Comment by blcarson** [comment]
You're a rock star - thank you!

**Comment by Alhadis** [comment]
@nathansobo and I both fixed [the same typo](https://github.com/atom/status-bar/commit/26fe0658feaffffbf303ddaf0766ded67a664128#diff-2e1bb36917ff76ab7308da52bc968501L74), which is all that triggered the conflict.

Amazing.

**Comment by nathansobo** [comment]
Thanks @Alhadis. This looks great and it will be nice to have this option.

**Comment by Alhadis** [comment]
If I weren't in the midst of crippling depression, I'd crown this the happiest day of my life. 👍  Thanks, Nathan.

**Comment by bronson** [comment]
Anyone know why I can't see this setting?  Atom 1.12, status-bar 1.4.1.  Would really like to use it!

(felt like including a screenshot for some reason...)

screen shot 2016-11-10 at 11 36 48 am

**Comment by Ben3eeE** [comment]
> Atom 1.12.0, status-bar 1.4.1.

It is available in Atom 1.13.

**Comment by bronson** [comment]
Ah, that's an easy explanation.  Thanks!

**Comment by pierreneter** [comment]
thanks! that's good news.

**Comment by blcarson** [comment]
It's in the latest beta now - working well so far.

**Pull request merged**
