### PR TITLE
Adding support for a top positioned status bar

### LINKED ISSUE #41: Add an option for placing the status bar on top
I was trying to get the status bar to be at the top, not bottom. Well, I got something usable, but its behavior is weird. I'm not yet good at neither JS or CS, even though I'm trying. And on top of that, it's not a check in configuration, it's a hardcoded mod, not cool.

So far, I swapped a call to `addBottomPanel` for a call to `addTopPanel` in `main.js`. It works fine. But at launch, it gets weird:

Weird screenshot

Notice the status bar sticking out into the tree view. After I open any file, this effect is just gone, even if I close everything again.

Effect gone

What could be causing this?

I'd appreciate it if this was implemented in the package anyway. I'm not feeling too confident about doing that myself just yet `:P`

### PR DESCRIPTION
**Pull request by chrisdrackett**
### Description of the Change

This adds a setting to position the status bar at the top of the window as an option.

I tried adding tests, but can't figure out why they don't pass. If anyone has thoughts let me know, I'm very new to working with atom, and this is my first foray into CoffeeScript and Jasmine.

### Applicable Issues

closes #41

### CODE REVIEW

**Comment by 50Wliu** [comment]
It looks like specs are passing on 1.16.0 but not on 1.17.0.  Are you running Atom Beta?

**Comment by chrisdrackett** [comment]
I am, I should have checked in 1.16.0, but they were passing in 1.17.0 before I made changes so I figured I was the issue ;)

**Comment by 50Wliu** [comment]
It might be that the new [Docks](https://github.com/atom/atom/pull/13977) feature is messing with your specs.

**Comment by chrisdrackett** [comment]
¯\_(ツ)_/¯ I know this code works with docks at least, I tested it manually!

**Comment by chrisdrackett** [comment]
tests pass now :)

**Comment by damieng** [comment]
This seems like an unusual setting to me - I can't think of any other software that puts status bars up at the top of the screen like this.  Thoughts @simurai ?

**Comment by chrisdrackett** [comment]
Here is a screenshot of my currently in progress theme where this is used:

screen shot 2017-09-07 at 1 00 11 pm

Depends on of you think of this bar as a status bar or a toolbar, I'd argue with the amount of interactivity its more a tool bar these days ;)

**Comment by damieng** [comment]
I agree it looks good in that screenshot - this feels like one of those options that really themes should be able to switch on rather than users as it will break incompatible themes and doesn't make sense without a supporting one (like frameless windows, tab sizing etc)

**Comment by simurai** [comment]
It feels a bit weird, but when styled like a macOS "tool bar", I agree that it looks great.

> @damieng this feels like one of those options that really themes should be able to switch on

Is that even possible to change it from a theme or does it need to be done in the status-bar package?

Something that would need to be changed in this PR: Have the status-bar underneath the custom title-bar when in full-width mode. Otherwise the traffic lights overlap. I think it's possible to set a [priority](https://atom.io/docs/api/v1.19.7/Workspace#instance-addTopPanel)?

status-bar

The [no-title-bar](https://atom.io/packages/no-title-bar) package will get in trouble, because it would add extra space to the tree-view instead of the status-bar at the top. So maybe there needs to be another class added to the body like `status-bar-top` that can be used as a hook? /cc @lexicalunit

screen shot 2017-09-09 at 5 12 57 pm

**Comment by chrisdrackett** [comment]
I wonder if I can take a stab at positioning this with the theme, I’ve also been meaning to look into how my theme in general interacts with the traffic lights… :)

**Comment by lexicalunit** [comment]
The way `no-title-bar` works is it adds left-padding to the tab-bar whenever the left dock is hidden, which we can finally detect using the new `atom.workspace.getLeftDock().observeVisible()` available in Atom `1.20.0-beta`.

This is selector for the element to which we add padding:

```
.no-title-bar:not(.fullscreen):not(.hidden-title-bar)
    atom-panel-container.left + atom-workspace-axis.vertical
    .pane:nth-child(1)
    .tab-bar
```

This element is highlighted in the following screenshots.

No padding when the dock is visible:

no-padding

Padding when the dock is hidden:

padding

But yeah, this assumes that the tab-bar is at the top of the frame and requires padding to accommodate the traffic lights. It would be really nice if there was an element in the document that corresponded to the traffic lights: I would just assign a width to that element itself.

**Comment by chrisdrackett** [comment]
Is it possible to have a theme that also provides functionality like a package? Curious if I can get control other than just css...

**Comment by chrisdrackett** [comment]
Looks like I'm able to get this working with css. This solution is probably better for my purposes as my theme doesn't really work with the status bar at the bottom anyways, one less thing for users to have to set!

**Comment by damieng** [comment]
That's great news.  Have you published your theme?  If so can you post a link here?

**Comment by chrisdrackett** [comment]
Its currently lacking in documentation and polish, but you can find it in its current state here:

https://github.com/chrisdrackett/bamboo-ui
https://github.com/chrisdrackett/bamboo-syntax

Hopefully I can keep finding time over the next couple weeks and get it worthy of publishing for other people to check out!

**Comment by Superpencil** [comment]
This screenshot is gorgeous @chrisdrackett, and I agree, @simurai & @damieng, that the status-bar at this point has become a toolbar: it is interactive, it has dropdowns, it contains buttons and actions, it also displays the path and name of the current file, so the only thing the title bar does now is the traffic lights... it would make a lot of sense to allow the status-bar to be put on the top imo 👍

**Pull request closed without merging**
